from text_processing import predict

def main():
    abstract = "Latar belakang: pemerintah mengusulkan pembentukan Badan Riset Nasional (BRN) seiring pembahasan RUU Perubahan UU No. 12 Tahun 2002 tentang Sisnas8000099 Iptek yang masih berproses di DPR RI, dengan mengangkat isu efisiensi anggaran riset dengan melebur seluruh lembaga riset pemerintah yang ada menjadii satu, namun dalam naskah akademik dan draft RUU yang diajukan tidak menyebutkan adanya nomenklatur BRN.  Pro dan kontra muncul termasuk dari kalangan peneliti kesehatan, karena bidang kesehatan merupakan bidang yang terus berkembang dalam hal riset dan pengembangann, dan memiliki kespesifikan riset tersendiri.  Tujuan: Mengeksplorasi wacana perlu tidaknya pembentukan BRN dari perspektif peneliti kesehatan dan memberikan rekomendasi terhadap organisasi BRN bila lembaga ini tetap dibentuk.  Metode: Studi kasus menggunakan data primer hasil Focus Group Discussion (FGD) dan didukung literature review berbagai sumber informasi terkait wacana pembentukan BRN, serta dianalisis secara deskriptif kualitatif.  Hasil: Penulis melakukann FGD dengan 47 peneliti kesehatan yang menghasilkan 3 opsi yaitu pertama tetap melebur lembaga riset menjadii BRN, kedua tidak perlu membentuk BRN, dan opsi terakhir BRN dibentuk tanpa melebur seluruh lembaga riset.  Opsi terakhir diharapkan dapat menengahi antara harapan pemerintah untuk membentuk BRN dengan keinginan para peneliti yang tidak mendukung peleburan lembaga-lembaga riset yang ada.  BRN tetap dibentuk sebagaii lembaga penunjang bagi seluruh lembaga riset yang ada sebagaii penghubung birokrasi, koordinasi dan sinergi.  Dalam hal ini BRN sangat tepat diposisikan sebagaii technostucture element bagi seluruh lembaga riset di Indonesia yang berperan sebagaii pengawas, penentu standar dan etik, penilai dan penghubung birokrasi, koordinasi dan sinergi sehingga efisiensi anggaran riset yang diinginkan pemerintah dapat terealisasi.  Kesimpulan dan Rekomendasi: Opsi terbaik yang dapat diambil pemerintah dan diharapkan diterima semua pihak adalah dengan tetap membentuk BRN tanpa melebur seluruh lembaga riset yang ada di Indonesia.  BRN dibentuk sebagaii technostructure element dan lembaga penunjang tersendiri yang berperan sebagaii pengawas, penilai, penentu standart, penghubung birokrasi, koordinasi dan sinergi seluruh lembaga riset yang ada di Indonesia"

    prediction = predict(abstract)


if __name__ == '__main__':
    main()